"""Create UserInterests table

Revision ID: 1f31cb600bc2
Revises: 
Create Date: 2025-01-21 10:23:40.852609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f31cb600bc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=40), nullable=False))
        batch_op.drop_column('entryno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entryno', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_column('event')

    # ### end Alembic commands ###
